pipeline_id: 1
extract_features:
  column_id: example_id
  impute_function: tsfresh.utilities.dataframe_functions.impute
  default_fc_parameters: MinimalFCParameters()
model_training:
  model_args:
  model: sklearn.ensemble.RandomForestClassifier
