pipeline_id: 2
model_training:
  model_args:
    generations: 300
    population_size: 50 
    verbosity: 2
    max_time_mins: 80
  model: tpot.TPOTClassifier
extract_features:
  column_id: example_id
  impute_function: tsfresh.utilities.dataframe_functions.impute
  default_fc_parameters: MinimalFCParameters()
